b=set()
b1=int(input("Enter a number: "))
b.add(b1)
b2=int(input("Enter another number: "))
b.add(b2)
b3=int(input("Enter another number: "))
b.add(b3)
b4=int(input("Enter another number: "))
b.add(b4)
b5=int(input("Enter another number: "))
b.add(b5)
b6=int(input("Enter another number: "))
b.add(b6)
b7=int(input("Enter another number: "))
b.add(b7)
b8=int(input("Enter another number: "))
b.add(b8)
print("The numbers you entered are: ", b)